# HeDoS Global Configuration
populationSize: 500
generationCount: 1000
crossoverProbability: 0.8
mutationProbability: 0.1
turnPenaltyFactor: 50.0
tournamentSize: 10
elitism: true
selectionType: GA.Selection.Tournament
mutationType: GA.Mutation.Random
crossoverType: GA.Crossover.Ordered
StartPoint: {x: 0.0, y: 0.0, z: 0.0}
targets:
  - {x: 31.0, y: 73.0, z: 60.0}
  - {x: 31.0, y: 59.0, z: 2.0}
  - {x: 99.0, y: 47.0, z: 60.0}
  - {x: 89.0, y: 50.0, z: 78.0}
  - {x: 4.0, y: 44.0, z: 40.0}
  - {x: 13.0, y: 88.0, z: 65.0}
  - {x: 51.0, y: 65.0, z: 53.0}
  - {x: 2.0, y: 64.0, z: 53.0}
  - {x: 63.0, y: 48.0, z: 35.0}
  - {x: 34.0, y: 54.0, z: 8.0}
  - {x: 36.0, y: 16.0, z: 5.0}
  - {x: 99.0, y: 28.0, z: 37.0}
  - {x: 93.0, y: 90.0, z: 78.0}
  - {x: 93.0, y: 14.0, z: 52.0}
  - {x: 85.0, y: 25.0, z: 42.0}
  - {x: 32.0, y: 67.0, z: 29.0}
  - {x: 14.0, y: 6.0, z: 80.0}
  - {x: 74.0, y: 27.0, z: 61.0}
  - {x: 53.0, y: 57.0, z: 78.0}
  - {x: 23.0, y: 68.0, z: 82.0}
  - {x: 87.0, y: 6.0, z: 28.0}
  - {x: 52.0, y: 9.0, z: 88.0}
  - {x: 59.0, y: 66.0, z: 98.0}
  - {x: 46.0, y: 52.0, z: 16.0}
  - {x: 87.0, y: 49.0, z: 1.0}
  - {x: 40.0, y: 11.0, z: 94.0}
  - {x: 30.0, y: 84.0, z: 93.0}
  - {x: 88.0, y: 22.0, z: 32.0}
  - {x: 96.0, y: 63.0, z: 50.0}
  - {x: 56.0, y: 66.0, z: 24.0}
  - {x: 35.0, y: 76.0, z: 1.0}
  - {x: 68.0, y: 7.0, z: 37.0}
  - {x: 51.0, y: 23.0, z: 61.0}
  - {x: 54.0, y: 82.0, z: 75.0}
  - {x: 50.0, y: 51.0, z: 27.0}
  - {x: 18.0, y: 76.0, z: 54.0}
  - {x: 3.0, y: 37.0, z: 73.0}
  - {x: 75.0, y: 43.0, z: 5.0}
  - {x: 29.0, y: 90.0, z: 98.0}
  - {x: 44.0, y: 54.0, z: 21.0}
  - {x: 99.0, y: 17.0, z: 52.0}
  - {x: 91.0, y: 9.0, z: 30.0}
  - {x: 32.0, y: 13.0, z: 70.0}
  - {x: 52.0, y: 63.0, z: 28.0}
  - {x: 59.0, y: 93.0, z: 28.0}
  - {x: 0.0, y: 86.0, z: 65.0}
  - {x: 56.0, y: 7.0, z: 91.0}
  - {x: 86.0, y: 37.0, z: 1.0}
  - {x: 89.0, y: 87.0, z: 37.0}
  - {x: 49.0, y: 49.0, z: 51.0}